# Command to execute flume-ng agent -n TwitterAgent -f <path of .conf file>



TwitterAgent.sources = Twitter 
TwitterAgent.channels = MemChannel 
TwitterAgent.sinks = HDFS
  
# Configuring the source 
# Assigning source type
#TwitterAgent.sources.Twitter.type = org.apache.flume.source.twitter.TwitterSource
TwitterAgent.sources.Twitter.type = com.cloudera.flume.source.TwitterSource
TwitterAgent.sources.Twitter.consumerKey=TCUomnQOppUnygMBFavmYaVqG
TwitterAgent.sources.Twitter.consumerSecret=1Xts4khf3lXQrYDIAxUwUr7clJw5XogFBcc5Uxh5fCQtk2SYSE
TwitterAgent.sources.Twitter.accessToken=1704496008-q7TrrEaLPFPC2DJwXl9vconm2MODvzY8G9Ey2Tw
TwitterAgent.sources.Twitter.accessTokenSecret=DvMlLi2vfkD6SoQKNW677GSwteNMPRMNRwel38mMsO71z

# Keywords to search for tweets
TwitterAgent.sources.Twitter.keywords= corona, coronavirus, covid19, lockdown, quarantine
TwitterAgent.sources.Twitter.language= en
# Configuring the sink

TwitterAgent.sinks.HDFS.channel=MemChannel
TwitterAgent.sinks.HDFS.type=hdfs
# path to store tweets
TwitterAgent.sinks.HDFS.hdfs.path=hdfs://namenode:9000/twitteranalytics/incremental
TwitterAgent.sinks.HDFS.hdfs.fileType=DataStream
TwitterAgent.sinks.HDFS.hdfs.writeformat=Text
TwitterAgent.sinks.HDFS.hdfs.batchSize=100
TwitterAgent.sinks.HDFS.hdfs.threadsPoolSize=2
TwitterAgent.sinks.HDFS.hdfs.round=true
TwitterAgent.sinks.HDFS.hdfs.rollSize=0
TwitterAgent.sinks.HDFS.hdfs.rollCount=0
TwitterAgent.sinks.HDFS.hdfs.rollInterval=67

# Configuring channel
TwitterAgent.channels.MemChannel.type=memory
TwitterAgent.channels.MemChannel.capacity=10000
TwitterAgent.channels.MemChannel.transactionCapacity=1000

TwitterAgent.sources.Twitter.channels = MemChannel
TwitterAgent.sinks.HDFS.channel = MemChannel
